CREATE TABLE IF NOT EXISTS rooms (
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS devices (
  id   INTEGER PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS room_devices (
  room_id INTEGER NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  device_id INTEGER NOT NULL UNIQUE REFERENCES devices(id) ON DELETE CASCADE,
  PRIMARY KEY (room_id, device_id)
);